# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-09-11 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarketApp', '0002_auto_20200911_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sxsdfoodtype',
            name='childtypenames',
            field=models.CharField(max_length=128),
        ),
    ]
